In [1]:
#import necessary library 
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm

<h3> problem statment</h3>
<h5>     A F&B manager wants to determine whether there is any significant difference in the diameter of the cutlet between two units. A randomly selected sample of cutlets was collected from both units and measured? Analyze the data and draw inferences at 5% significance level. Please state the assumptions and tests that you carried out to check validity of the assumptions.<h5>
    
    <h3>Assumption</h3>
    <h5>Setting H0 and H1
<b>µ1 is the mean for unit 1<b>
    <br>
    <b>µ2 is the mean for unit 2</b><br>
H0 : µ1= µ 2 (µ 1- µ 2=0) there is no significant difference <br>
H1: µ 1 ≠ µ 2(µ 1- µ 2≠0) there is a significant difference<br>
<pre>Alpha is α= 0.05
Critical value is  Z=1.645
Find the var1 and var2 from the sample given 
σ1=0.083179
σ2=0.117924
<pre>

    </h5>

In [4]:
#load the dataset
df1=pd.read_csv('G:\\Data Science\\Assignment\\03\\Cutlets.csv')

In [7]:
unitA,unitB=pd.Series(df1.iloc[:,0]),pd.Series(df1.iloc[:,1])
print(unitA,unitB)

0     6.8090
1     6.4376
2     6.9157
3     7.3012
4     7.4488
5     7.3871
6     6.8755
7     7.0621
8     6.6840
9     6.8236
10    7.3930
11    7.5169
12    6.9246
13    6.9256
14    6.5797
15    6.8394
16    6.5970
17    7.2705
18    7.2828
19    7.3495
20    6.9438
21    7.1560
22    6.5341
23    7.2854
24    6.9952
25    6.8568
26    7.2163
27    6.6801
28    6.9431
29    7.0852
30    6.7794
31    7.2783
32    7.1561
33    7.3943
34    6.9405
Name: Unit A, dtype: float64 0     6.7703
1     7.5093
2     6.7300
3     6.7878
4     7.1522
5     6.8110
6     7.2212
7     6.6606
8     7.2402
9     7.0503
10    6.8810
11    7.4059
12    6.7652
13    6.0380
14    7.1581
15    7.0240
16    6.6672
17    7.4314
18    7.3070
19    6.7478
20    6.8889
21    7.4220
22    6.5217
23    7.1688
24    6.7594
25    6.9399
26    7.0133
27    6.9182
28    6.3346
29    7.5459
30    7.0992
31    7.1180
32    6.6965
33    6.5780
34    7.3875
Name: Unit B, dtype: float64


In [9]:
# 2-sample 2-tail ttest:   stats.ttest_ind(array1,array2)     # ind -> independent samples
#do the z-two tail test to see if there is a significant different between 2 means or not
test=stats.ttest_ind(unitA,unitB)
print(test)

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.47223947245995)


In [10]:
test[0]

0.7228688704678063

In [11]:
test[1]

0.47223947245995

<h3>Conclusion</h3>
<h4><b>P-value is greater than Alpha 0.05 so we won't reject the null and will accept it<b></h4>

<h3>Problem Statement<h3>
<pre>A hospital wants to determine whether there is any difference in the average Turn Around Time (TAT) of reports of the laboratories on their preferred list. They collected a random sample and recorded TAT for reports of 4 laboratories. TAT is defined as sample collected to report dispatch.
   
  Analyze the data and determine whether there is any difference in average TAT among the different laboratories at 5% significance level.
<pre>

<pre>Setting H0 and H1
µ1 is the mean for lab1
µ2 is the mean for lab2
µ3 is the mean for lab3
µ4 is the mean for lab4
H0 : µ1= µ 2= µ 3 = µ 4  (µ 1- µ 2- µ 3 - µ 4 =0) there is no significant difference between all mean
H1: µ 1 ≠ µ 2 =µ 3= µ 2 (µ 1- µ 2- µ 3- µ 4 ≠0) there is a significant difference at least one mean different 
Alpha is α= 0.05
<pre>

In [18]:
#load the data
df2=pd.read_csv('G:\\Data Science\\Assignment\\03\\labTAT.csv')
df2.iloc[:,0:4]

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0          185.35        165.53        176.70        166.13
1          170.49        185.91        198.45        160.79
2          192.77        194.92        201.23        185.18
3          177.33        183.00        199.61        176.42
4          193.41        169.57        204.63        152.60
..            ...           ...           ...           ...
115        178.49        170.66        193.80        172.68
116        176.08        183.98        215.25        177.64
117        202.48        174.54        203.99        170.27
118        182.40        197.18        194.52        150.87
119        182.09        215.17        221.49        162.21

[120 rows x 4 columns]

In [20]:
anova=stats.f_oneway(df2.iloc[:,0],df2.iloc[:,1],df2.iloc[:,2],df2.iloc[:,3])
print(anova)

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)


In [21]:
#compare with 0.05
if(anova[1]>0.05):
    print('Failed to reject the H0')
else:
    print("Null hypothesis rejected")

Null hypothesis rejected


# 

<h3>Problem Statment<h3>
    <pre>Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are similar across regions.
 <pre>
 

In [29]:
#load data
df3=pd.read_csv('G:\\Data Science\\Assignment\\03\\BuyerRatio.csv')
df3=df3.iloc[:2,0:5]# not im doing this cause i've edited in the original file and do caculation there 
df3.head()

Observed Values (O) East    West   North  South
0               Males   50   142.0   131.0   70.0
1             Females  435  1523.0  1356.0  750.0

In [30]:
df_table=df3.iloc[:,1:6]
df_table

East    West   North  South
0   50   142.0   131.0   70.0
1  435  1523.0  1356.0  750.0

In [41]:
# Make dimensional array for the observation
O=np.array([[50,142,131,70],[435,1523,1356,750]])
O

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]])

In [42]:
# applay chia
val=stats.chi2_contingency(O)

In [45]:
print("Chi2 value is: ",val[0])#(Chi2 stats value, p_value, df, expected obsvations)
print("P_value is: ",val[1])
print("Dgree of freedom FD: ",val[2])
print("Expexted table for the observation: ",val[3])

Chi2 value is:  1.595945538661058
P_value is:  0.6603094907091882
Dgree of freedom FD:  3
Expexted table for the observation:  [[  42.76531299  146.81287862  131.11756787   72.30424052]
 [ 442.23468701 1518.18712138 1355.88243213  747.69575948]]


<h3> Conclusion</h3>
<h4> We observed that P-value is greater than Alph wich is 0.05 so we will to reject the Null Hypothesis<h4>
    

# 

<h3>Problem Statment<h3>
    <pre>TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain %  of the customer order forms. Any error in order form renders it defective and has to be reworked before processing.  The manager wants to check whether the defective %  varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences
<pre>

In [47]:
#load the data
df4=pd.read_csv('G:\\Data Science\\Assignment\\03\\costomer+OrderForm.csv')
df4.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [56]:
#calculate each observ for each country -- error and Eefective
l1=[]
l2=[]
def Chi(x):
    x=x.value_counts()
    l1.append(x[0])
    l2.append(x[1])
Chi(df4.Phillippines)
Chi(df4.Indonesia)
Chi(df4.Malta)
Chi(df4.India)

In [59]:
#combine the 2 list
O=[l1,l2]
O

[[271, 267, 269, 280], [29, 33, 31, 20]]

In [65]:
# Chi2 contengency independence test
answer=stats.chi2_contingency(O) # o/p is (Chi2 stats value, p_value, df, expected obsvations

In [66]:
print("Chi2 value is: ",answer[0])#(Chi2 stats value, p_value, df, expected obsvations)
print("P_value is: ",answer[1])
print("Dgree of freedom FD: ",answer[2])
print("Expexted table for the observation: ",answer[3])

Chi2 value is:  3.858960685820355
P_value is:  0.2771020991233135
Dgree of freedom FD:  3
Expexted table for the observation:  [[271.75 271.75 271.75 271.75]
 [ 28.25  28.25  28.25  28.25]]


<h3>Conclusion<h3>
    P-value is greater than Alpha 0.05 so we will Accept the Null Hypothesis